# Generated by Django 2.1.7 on 2019-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('est_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('amasiado', 'Amasiado(a)'), ('separado', 'Separado(a)'), ('viuvo', 'Viúvo(a)'), ('divorciado', 'Divorciado')], max_length=50, verbose_name='Estado Civil')),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=50, null=True)),
                ('cpfcnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('uf', models.CharField(blank=True, choices=[('ac', 'AC'), ('al', 'AL'), ('am', 'AM'), ('ap', 'AP'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('ro', 'RO'), ('rr', 'RR'), ('rs', 'RS'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=40, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
